version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seguridad_backend
    ports:
      - "8080:8080"  # Mapea el puerto 8080 del contenedor al 8080 del host
    working_dir: /app
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=12345
      - DB_NAME=bd_desplegada
      - APP_PORT=8080
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:10.5
    container_name: db_seguridad
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: bd_desplegada
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"  # Mapea el puerto 3306 del contenedor al 3307 del host
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge